# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site wide configuration

title:            Perpetually Learning
locale:           en_US
url:              http://www.bradaallen.com

description: > # this means to ignore newlines until "baseurl:"
  Brad Allen's personal blog. I love building things (and learning how to build
  new things). Preferably those that scale. Keywords: Product Management, Data Science,
  Data Engineering, Python, Stanford, Stanford GSB, Penn State, Pennsylvania, TFA,
  Teach For America, Bain, Embrace, Aclima, Peloton Technology, Mechatronics, C+
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.0"
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed  

# Site owner
owner:
  name: Brad Allen
  avatar: Brad_Thumbs_Up.jpg
  bio: "Doing a little more each day."
  email: bradaallen@gmail.com
  disqus-shortname: 
  twitter: bradaallen
  facebook: bradaallen
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bradaallen
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: bradaallen
  xing: #username
  instagram: bradaallen
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
